INSERT ALL
INTO test (id_test, nombretest, descripcion, programa, unidad, autor, fechacreacion) VALUES (1,'evaluacion 1', 'pseudocodigo', 'Full Stack Java', '1', 'Brian Guzman', TO_DATE('2020-02-04', 'YYYY-MM-DD'))
INTO test (id_test, nombretest, descripcion, programa, unidad, autor, fechacreacion) VALUES (2,'evaluacion 2', 'Java', 'Full Stack Java', '2', 'Brian Guzman', TO_DATE('2020-02-17', 'YYYY-MM-DD'))
INTO test (id_test, nombretest, descripcion, programa, unidad, autor, fechacreacion) VALUES (3,'evaluacion 3 (deficiente a proposito)', 'BBDD', 'Full Stack Java', '3', 'Brian Guzman', TO_DATE('2020-03-21', 'YYYY-MM-DD'))
INTO test (id_test, nombretest, descripcion, programa, unidad, autor, fechacreacion) VALUES (4,'evaluacion 4 (deficiente a proposito)', 'HTML', 'Full Stack Java', '4', 'Brian Guzman', TO_DATE('2020-04-21', 'YYYY-MM-DD'))
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (1, 'Pregunta 1', 0.1, 1)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (2, 'Pregunta 2', 0.1, 1)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (3, 'Pregunta 3', 0.1, 1)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (4, 'Pregunta 4', 0.1, 1)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (5, 'Pregunta 5', 0.1, 1)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (6, 'Pregunta 6', 0.1, 1)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (7, 'Pregunta 7', 0.1, 1)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (8, 'Pregunta 8', 0.1, 1)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (9, 'Pregunta 9', 0.1, 1)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (10, 'Pregunta 10', 0.1, 1)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (11, 'Pregunta 1', 0.1, 2)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (12, 'Pregunta 2', 0.1, 2)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (13, 'Pregunta 3', 0.1, 2)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (14, 'Pregunta 4', 0.1, 2)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (15, 'Pregunta 5', 0.1, 2)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (16, 'Pregunta 6', 0.1, 2)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (17, 'Pregunta 7', 0.1, 2)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (18, 'Pregunta 8', 0.1, 2)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (19, 'Pregunta 9', 0.1, 2)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (20, 'Pregunta 10', 0.1, 2)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (21, 'Pregunta 1', 0.33, 4)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (22, 'Pregunta 2', 0.33, 4)
INTO preguntas (id_pregunta, enunciado, puntajeasociado, id_test) VALUES (23, 'Pregunta 3', 0.34, 4)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (5000, 'Alternativa A', 1, 1, 21)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (5001, 'Alternativa B', 0, 0, 21)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (5002, 'Alternativa A', 1, 0.33, 22)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (5003, 'Alternativa B', 1, 0.33, 22)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (5004, 'Alternativa C', 1, 0.34, 22)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (5005, 'Alternativa A', 0, 0, 23)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (5006, 'Alternativa B', 0, 0, 23)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (5007, 'Alternativa C', 0, 0, 23)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (1, 'Alternativa A', 1, 1, 1)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (2, 'Alternativa B', 0, 0, 1)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (3, 'Alternativa C', 0, 0, 1)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (4, 'Alternativa D', 0, 0, 1)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (5, 'Alternativa A', 0, 0, 2)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (6, 'Alternativa B', 1, 1, 2)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (7, 'Alternativa C', 0, 0, 2)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (8, 'Alternativa D', 0, 0, 2)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (9, 'Alternativa A', 0, 0, 3)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (10, 'Alternativa B', 0, 0, 3)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (11, 'Alternativa C', 1,1, 3)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (12, 'Alternativa D', 0, 0, 3)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (13, 'Alternativa A', 0, 0, 4)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (14, 'Alternativa B', 0, 0, 4)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (15, 'Alternativa C', 0, 0, 4)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (16, 'Alternativa D', 1, 1, 4)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (17, 'Alternativa A', 1, 0.5, 5)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (18, 'Alternativa B', 1, 0.5, 5)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (19, 'Alternativa C', 0, 0, 5)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (20, 'Alternativa D', 0, 0, 5)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (21, 'Alternativa A', 0, 0, 6)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (22, 'Alternativa B', 0, 0, 6)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (23, 'Alternativa C', 1, 0.5, 6)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (24, 'Alternativa D', 1, 0.5, 6)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (25, 'Alternativa A', 1, 0.33, 7)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (26, 'Alternativa B', 1, 0.33, 7)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (27, 'Alternativa C', 1, 0.34, 7)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (28, 'Alternativa D', 0, 0, 7)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (29, 'Alternativa A', 0, 0, 8)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (30, 'Alternativa B', 1, 0.33, 8)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (31, 'Alternativa C', 1, 0.33, 8)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (32, 'Alternativa D', 1, 0.34, 8)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (33, 'Alternativa A', 1, 0.5, 9)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (34, 'Alternativa B', 0, 0, 9)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (35, 'Alternativa C', 0, 0, 9)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (36, 'Alternativa D', 1, 0.5, 9)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (37, 'Alternativa A', 1, 0.33, 10)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (38, 'Alternativa B', 0, 0, 10)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (39, 'Alternativa C', 1, 0.33, 10)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (40, 'Alternativa D', 1, 0.34, 10)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (41, 'Alternativa A', 1, 1, 11)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (42, 'Alternativa B', 0, 0, 11)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (43, 'Alternativa C', 0, 0, 11)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (44, 'Alternativa D', 0, 0, 11)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (45, 'Alternativa A', 0, 0, 12)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (46, 'Alternativa B', 1, 1, 12)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (47, 'Alternativa C', 0, 0, 12)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (48, 'Alternativa D', 0, 0, 12)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (49, 'Alternativa A', 0, 0, 13)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (50, 'Alternativa B', 0, 0, 13)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (51, 'Alternativa C', 1,1, 13)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (52, 'Alternativa D', 0, 0, 13)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (53, 'Alternativa A', 0, 0, 14)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (54, 'Alternativa B', 0, 0, 14)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (55, 'Alternativa C', 0, 0, 14)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (56, 'Alternativa D', 1, 1, 14)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (57, 'Alternativa A', 1, 0.5, 15)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (58, 'Alternativa B', 1, 0.5, 15)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (59, 'Alternativa C', 0, 0, 15)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (60, 'Alternativa D', 0, 0, 15)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (61, 'Alternativa A', 0, 0, 16)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (62, 'Alternativa B', 0, 0, 16)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (63, 'Alternativa C', 1, 0.5, 16)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (64, 'Alternativa D', 1, 0.5, 16)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (65, 'Alternativa A', 1, 0.33, 17)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (66, 'Alternativa B', 1, 0.33, 17)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (67, 'Alternativa C', 1, 0.34, 17)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (68, 'Alternativa D', 0, 0, 17)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (69, 'Alternativa A', 0, 0, 18)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (70, 'Alternativa B', 1, 0.33, 18)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (71, 'Alternativa C', 1, 0.33, 18)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (72, 'Alternativa D', 1, 0.34, 18)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (73, 'Alternativa A', 1, 0.5, 19)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (74, 'Alternativa B', 0, 0, 19)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (75, 'Alternativa C', 0, 0, 19)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (76, 'Alternativa D', 1, 0.5, 19)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (77, 'Alternativa A', 1, 0.33, 20)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (78, 'Alternativa B', 0, 0, 20)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (79, 'Alternativa C', 1, 0.33, 20)
INTO alternativas (id_alternativa, descripcion, correcta_incorrecta, porcentajecorrecta, id_pregunta) VALUES (80, 'Alternativa D', 1, 0.34, 20)
SELECT * FROM dual;