INSERT ALL
INTO cursos (id_curso, nombrecurso, horainicio, horafin) VALUES (1,'Full Stack Java 1', '13:00','18:00')
INTO cursos (id_curso, nombrecurso, horainicio, horafin) VALUES (2,'Full Stack Java 2', '17:00','22:00')
INTO cursos (id_curso, nombrecurso, horainicio, horafin) VALUES (3,'Diseñador UX', '18:00','23:00')
INTO alumnos (id_alumno, nombre, apellido) VALUES (1,'Manuel', 'Lillo')
INTO alumnos (id_alumno, nombre, apellido) VALUES (2,'Takeshi', 'Kita')
INTO alumnos (id_alumno, nombre, apellido) VALUES (3,'Cristobal', 'Latorre')
INTO alumnos (id_alumno, nombre, apellido) VALUES (4,'Andres', 'Barroso')
INTO alumnos (id_alumno, nombre, apellido) VALUES (5,'Ricardo', 'Hermosilla')
INTO alumnos (id_alumno, nombre, apellido) VALUES (6,'Juan Carlos', 'Tolorza')
INTO alumnos (id_alumno, nombre, apellido) VALUES (7,'Matias', 'Flores')
INTO alumnos (id_alumno, nombre, apellido) VALUES (8,'Alexis', 'Ruiz')
INTO alumnos (id_alumno, nombre, apellido) VALUES (9,'Trinidad', 'Gaete')
INTO alumnos (id_alumno, nombre, apellido) VALUES (10,'Karla', 'Gomez')
INTO alumnos (id_alumno, nombre, apellido) VALUES (11,'Fernando', 'Fernandez')
INTO alumnos (id_alumno, nombre, apellido) VALUES (12,'Gonzalo', 'Gonzalez')
INTO alumnos (id_alumno, nombre, apellido) VALUES (13,'Rodrigo', 'Rodriguez')
INTO alumnos (id_alumno, nombre, apellido) VALUES (14,'Alvaro', 'Alvarez')
INTO alumnos (id_alumno, nombre, apellido) VALUES (15,'Martin', 'Martinez')
INTO alumnos (id_alumno, nombre, apellido) VALUES (16,'Enrique', 'Enriquez')
INTO alumnos (id_alumno, nombre, apellido) VALUES (17,'Domingo', 'Dominguez')
INTO alumnos (id_alumno, nombre, apellido) VALUES (18,'Benito', 'Benitez')
INTO alumnos (id_alumno, nombre, apellido) VALUES (19,'Carmen', 'Carmona')
INTO alumnos (id_alumno, nombre, apellido) VALUES (20,'Hernan', 'Hernandez')
INTO cursosalumnos (id_curso, id_alumno) VALUES (1,1)
INTO cursosalumnos (id_curso, id_alumno) VALUES (1,2)
INTO cursosalumnos (id_curso, id_alumno) VALUES (1,3)
INTO cursosalumnos (id_curso, id_alumno) VALUES (1,4)
INTO cursosalumnos (id_curso, id_alumno) VALUES (1,5)
INTO cursosalumnos (id_curso, id_alumno) VALUES (1,6)
INTO cursosalumnos (id_curso, id_alumno) VALUES (1,7)
INTO cursosalumnos (id_curso, id_alumno) VALUES (1,8)
INTO cursosalumnos (id_curso, id_alumno) VALUES (1,9)
INTO cursosalumnos (id_curso, id_alumno) VALUES (1,10)
INTO cursosalumnos (id_curso, id_alumno) VALUES (2,11)
INTO cursosalumnos (id_curso, id_alumno) VALUES (2,12)
INTO cursosalumnos (id_curso, id_alumno) VALUES (2,13)
INTO cursosalumnos (id_curso, id_alumno) VALUES (2,14)
INTO cursosalumnos (id_curso, id_alumno) VALUES (2,15)
INTO cursosalumnos (id_curso, id_alumno) VALUES (2,16)
INTO cursosalumnos (id_curso, id_alumno) VALUES (2,17)
INTO cursosalumnos (id_curso, id_alumno) VALUES (2,18)
INTO cursosalumnos (id_curso, id_alumno) VALUES (2,19)
INTO cursosalumnos (id_curso, id_alumno) VALUES (2,20)
INTO cursosalumnos (id_curso, id_alumno) VALUES (3,20)
INTO cursostest (id_curso, id_test) VALUES (1,1)
INTO cursostest (id_curso, id_test) VALUES (1,2)
INTO cursostest (id_curso, id_test) VALUES (2,1)
INTO cursostest (id_curso, id_test) VALUES (2,2)
SELECT * FROM dual;



